package conf

const (
	URLIdentifyCodeByEmail = "/user/captcha-by-email"
	URLIdentifyCode        = "/user/captcha"
	URLRegisterLogin       = "/user/login-register"
	URLCheckPassword       = "/user/check-password"
	URLLoginOut            = "/user/login-out"
	URLUpdateNickName      = "/user/nick-name"
	URLUpdateGender        = "/user/gender"
	URLUpdateSummary       = "/user/summary"
	URLUpdateProvinceCity  = "/user/province-city"
	URLUpdateBirthday      = "/user/birthday"
	URLUpdatePassword      = "/user/password"
	URLPublishArticle      = "/article/publish"
	URLGetArticleList      = "/article/list"
	URLGetArticleDetail    = "/article/detail"
	URLDelArticle          = "/article/del"
	URLGetUserInfoByAid    = "/article/get-user-info-by-aid"
	URLExtractSummary      = "/article/extract-summary"
	URLLikeCollectArticle  = "/article/like-collect"
	URLGetColumnList       = "/column/list"
	URLFileUpload          = "/file/upload"
	URLWsConnection        = "/ws"
	URLLike                = "/like"
)
